### ISSUE TITLE
What Options Does It Take?

### ISSUE THREAD

**Issue by opticyclic** [jwilk/demoostrap#1]
I normally run debootstrap like this to bootstrap ubuntu into a directory call chroot

    sudo debootstrap --verbose --arch=amd64 zesty chroot 

How do I do this with demoostrap?

**Comment by jwilk** [comment]
```
sudo demoostrap chroot
```

There's no way to specify suite (such as `zesty`) or architecture, because packages from the host are being used.

There's no `--verbose` option at the moment, but I could easily add one.
